const samplePlaces = [
  {
    _id: '1',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657121/samples/landscapes/landscape-panorama.jpg',
    address: '123 Main Street, New York',
    title: 'Cozy Apartment in City Center',
    price: '₹3000',
    extraInfo: 'Newly renovated apartment with modern amenities.',
    perks: ['Free Wi-Fi', 'Gym access', 'Parking'],
    maxGuests: 4,
  },
  {
    _id: '2',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657121/samples/landscapes/nature-mountains.jpg',
    address: '456 Sunset Blvd, Los Angeles',
    title: 'Luxury Villa with Pool',
    price: '₹12000',
    extraInfo: 'Private villa with stunning ocean views.',
    perks: ['Private pool', 'Chef service', 'Spa access'],
    maxGuests: 8,
  },
  {
    _id: '3',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657120/samples/landscapes/architecture-signs.jpg',
    address: '789 Pine Road, Colorado',
    title: 'Mountain Cabin Retreat',
    price: '₹5000',
    extraInfo: 'Secluded cabin perfect for nature lovers.',
    perks: ['Fireplace', 'Hiking trails', 'Pet-friendly'],
    maxGuests: 6,
  },
  {
    _id: '4',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657120/samples/ecommerce/car-interior-design.jpg',
    address: '101 Ocean Drive, Miami',
    title: 'Beachfront Bungalow',
    price: '₹8000',
    extraInfo: 'Direct beach access with private patio.',
    perks: ['Beach chairs', 'Water sports equipment', 'BBQ grill'],
    maxGuests: 5,
  },
  {
    _id: '5',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657120/samples/people/bicycle.jpg',
    address: '12 Greenway Lane, Seattle',
    title: 'Urban Loft with City View',
    price: '₹6500',
    extraInfo: 'Stylish loft in the heart of the city.',
    perks: ['Rooftop terrace', 'Concierge service', 'Bicycle rental'],
    maxGuests: 3,
  },
  {
    _id: '6',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657119/samples/animals/reindeer.jpg',
    address: '33 Lakeview Drive, Austin',
    title: 'Rustic Farmhouse with Garden',
    price: '₹4500',
    extraInfo: 'Charming farmhouse with a large garden.',
    perks: ['Organic garden', 'Farm animals', 'Outdoor dining'],
    maxGuests: 7,
  },
  {
    _id: '7',
    image: 'https://hblimg.mmtcdn.com/content/hubble/img/lakshadweep/mmt/destination/m_Lakshadweep_l_580_870.jpg',
    address: '10 Market Street, Chicago',
    title: 'Modern Studio Apartment',
    price: '₹7000',
    extraInfo: 'Compact studio with city skyline views.',
    perks: ['Smart home features', '24-hour security', 'Laundry facilities'],
    maxGuests: 2,
  },
  {
    _id: '8',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657120/samples/ecommerce/shoes.jpg',
    address: '555 Beach Road, Hawaii',
    title: 'Seaside Villa with Private Beach',
    price: '₹15000',
    extraInfo: 'Exclusive villa with private beach access.',
    perks: ['Private beach', 'Infinity pool', 'Personal butler'],
    maxGuests: 10,
  },
  {
    _id: '9',
    image: 'https://picsum.photos/seed/picsum/200/300',
    address: '33 Lakeview Drive, Austin',
    title: 'Rustic Farmhouse with Garden',
    price: '₹4500',
    extraInfo: 'Charming farmhouse with a large garden.',
    perks: ['Organic garden', 'Farm animals', 'Outdoor dining'],
    maxGuests: 7,
  },
  {
    _id: '10',
    image: 'https://hblimg.mmtcdn.com/content/hubble/img/lakshadweep/mmt/destination/m_Lakshadweep_l_580_870.jpg',
    address: '10 Market Street, Chicago',
    title: 'Modern Studio Apartment',
    price: '₹7000',
    extraInfo: 'Compact studio with city skyline views.',
    perks: ['Smart home features', '24-hour security', 'Laundry facilities'],
    maxGuests: 2,
  },
  {
    _id: '11',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657120/samples/ecommerce/shoes.jpg',
    address: '555 Beach Road, Hawaii',
    title: 'Seaside Villa with Private Beach',
    price: '₹15000',
    extraInfo: 'Exclusive villa with private beach access.',
    perks: ['Private beach', 'Infinity pool', 'Personal butler'],
    maxGuests: 10,
  },
  {
    _id: '12',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657119/samples/animals/reindeer.jpg',
    address: '33 Lakeview Drive, Austin',
    title: 'Rustic Farmhouse with Garden',
    price: '₹4500',
    extraInfo: 'Charming farmhouse with a large garden.',
    perks: ['Organic garden', 'Farm animals', 'Outdoor dining'],
    maxGuests: 7,
  },
  {
    _id: '13',
    image: 'https://hblimg.mmtcdn.com/content/hubble/img/lakshadweep/mmt/destination/m_Lakshadweep_l_580_870.jpg',
    address: '10 Market Street, Chicago',
    title: 'Modern Studio Apartment',
    price: '₹7000',
    extraInfo: 'Compact studio with city skyline views.',
    perks: ['Smart home features', '24-hour security', 'Laundry facilities'],
    maxGuests: 2,
  },
  {
    _id: '14',
    image: 'https://res.cloudinary.com/dqskebjcf/image/upload/v1724657119/samples/bike.jpg',
    address: '555 Beach Road, Hawaii',
    title: 'Seaside Villa with Private Beach',
    price: '₹15000',
    extraInfo: 'Exclusive villa with private beach access.',
    perks: ['Private beach', 'Infinity pool', 'Personal butler'],
    maxGuests: 10,
  },
];

export default samplePlaces;